name: flutter_cs16_theme
description: "A Counter-Strike 1.6 inspired UI theme for Flutter applications."
version: 0.1.0
homepage:

environment:
  sdk: ">=3.4.4 <4.0.0" # Ensures compatibility with Dart 3.4.4+
  flutter: ">=1.17.0"   # Supports Flutter 1.17.0 and above

dependencies:
  flutter:
    sdk: flutter # Core Flutter dependency

dev_dependencies:
  flutter_test:
    sdk: flutter # Required for running tests
  flutter_lints: ^3.0.0 # Enforces best practices and code linting

flutter:
  # # Specifies the assets used in this package.
  # assets:
  #   - assets/screenshot.png # Example image used in README
  
  # # Defines custom fonts used in the package.
  # fonts:
  #   - family: ArialPixel
  #     fonts:
  #       - asset: assets/fonts/ArialPixel.ttf

