name: Deploy Flutter Web from `examples/demo/`

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'
          channel: stable

      - name: Enable Flutter Web
        run: |
          cd examples/demo
          flutter config --enable-web

      - name: Install Dependencies
        run: |
          cd examples/demo
          flutter pub get

      - name: Build Flutter Web with Base Path
        run: |
          cd examples/demo
          flutter build web --release --base-href "/flutter-cs16-theme/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: examples/demo/build/web
          publish_branch: gh-pages
